package com.example.pridestarappschallenge.models

import com.google.gson.annotations.SerializedName
import java.io.Serializable

//Network model class generated by JsonToKotlinDataClass plugin
data class HomeAPIResult(
    @SerializedName("copyright")
    var copyright: String,
    @SerializedName("last_updated")
    var lastUpdated: String,
    @SerializedName("num_results")
    var numResults: Int,
    @SerializedName("results")
    var storiesResults: List<StoriesResult>,
    @SerializedName("section")
    var section: String,
    @SerializedName("status")
    var status: String
): Serializable